from python:3-alpine3.15
WORKDIR /Users/ananyobanerjee/Documents/Projects/Python
COPY . /Users/ananyobanerjee/Documents/Projects/Python
RUN pip3 install -r requirements.txt
EXPOSE 3000
cmd python3 main.py
