apiVersion: v1
kind: Pod
metadata:
 name: restinterface
 labels:
  app: restinterface
  tier: frontend
spec:
 containers:
 - name: restinterface
   image: ananyobanerjee/myrestapi:latest
   imagePullPolicy: Always
   