apiVersion: v1
kind: Service
metadata:
 name: restservicepod-service
spec:
 type: NodePort
 ports: 
  - targetPort: 3000
    port: 3005
    nodePort: 30040
 selector:
   app: restinterface
   tier: frontend