name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push the Docker image
      run: 
        echo "${{ SECRETS.DOCKERPASSWORD }}" | docker login -u "ananyobanerjee" --password-stdin
        docker build ./Python -t ananyobanerjee/myrestapi
        docker push ananyobanerjee/myrestapi
